version: '2.1'
project: 'finalid' # added to work with sloppy.io
services:
  web:
    build:
      context: ../../.
      dockerfile: ./docker/Prod/Dockerfile
    ports:
    - "80:80"
    links:
    - redis
  redis:
    image: redis