version: '2.1'
services:
  web:
    build:
      context: ../../.
      dockerfile: ./docker/Prod/Dockerfile
    ports:
    - "80:80"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}