version: '2.1'
services:
  web:
    build:
      context: ../../.
      dockerfile: ./docker/Prod/Dockerfile
    ports:
    - "80:80"
    links:
    - redis.database.finalid
  redis.database.finalid:
    image: redis