version: '2.1'
services:
  web:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    ports:
    - "5000:5000"
    volumes:
    - ../../.:/code
    - logvolume01:/var/log
    links:
    - redis
    working_dir: /code
    command: dotnet watch run --urls http://0.0.0.0:5000
  redis:
    image: redis
volumes:
  logvolume01: {}