version: '2.1'
services:
  web:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    ports:
    - "5000:5000"
    volumes:
    - ../../.:/code
    - logvolume01:/var/log
    links:
    - redis
    command: [ "dotnet", "watch", "run", "/code/finalid.web.csproj" ]
    # command: dir /code/
  redis:
    image: redis
volumes:
  logvolume01: {}